application:
  answers: 3
  path-en: /questions_en.csv
  path-ru: /questions_ru.csv

spring:
  shell:
    interactive:
      enabled: false
  main:
    allow-circular-references: true
    web-application-type: NONE